pretrained_model_path: ./checkpoints/CompVis/stable-diffusion-v1-4
output_dir: /content/drive/Shareddrives/CS236/final_project/outputs/fewshot/animal_walking
train_data:
  video_paths:
  - training_videos/animal_walking/bear_walking_in_river.mp4
  - training_videos/animal_walking/rhino_walking_on_grass.mp4
  - training_videos/animal_walking/polar_bear_walking_on_snow.mp4
  - training_videos/animal_walking/tiger_walking_in_river.mp4
  - training_videos/animal_walking/tiger_walking_in_zoo.mp4
  - training_videos/animal_walking/elephant_walking_on_grassy_land.mp4
  - training_videos/animal_walking/elephant_walking_slowly_on_grassland.mp4
  - training_videos/animal_walking/elephant_walking_on_grassland_with_mountain_in_background.mp4
  - training_videos/animal_walking/bear_walking_through_grass_beside_a_lake.mp4
  - training_videos/animal_walking/bear_walking_in_front_of_bushes.mp4
  - training_videos/animal_walking/elephant_walking_in_tall_grass.mp4
  - training_videos/animal_walking/lion_walking_towards_another_lion.mp4
  - training_videos/animal_walking/lion_walking_in_tall_grass.mp4
  - training_videos/animal_walking/lion_walking_on_grassland.mp4
  - training_videos/animal_walking/lion_walking_on_dirt.mp4
  - training_videos/animal_walking/rhino_walking_in_tall_grass.mp4
  prompts:
  - bear walking in river
  - rhino walking on grass
  - polar bear walking on snow
  - tiger walking in river
  - tiger walking in zoo
  - elephant walking on grassy land
  - elephant walking slowly on grassland
  - elephant walking on grassland with mountain in background
  - bear walking through grass beside a lake
  - bear walking in front of bushes
  - elephant walking in tall grass
  - lion walking towards another lion
  - lion walking in tall grass
  - lion walking on grassland
  - lion walking on dirt
  - rhino walking in tall grass
  n_sample_frames: 16
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
  - mickey mouse is skiing on the snow
  - spider man is skiing on the beach, cartoon style
  - wonder woman, wearing a cowboy hat, is skiing
  - a man, wearing pink clothes, is skiing at sunset
  video_length: 16
  width: 512
  height: 320
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
lr_scheduler: linear
lr_warmup_steps: 300
train_batch_size: 1
max_train_steps: 1600
checkpointing_steps: 500
resume_from_checkpoint: /content/drive/Shareddrives/CS236/final_project/outputs/fewshot/animal_walking/checkpoint-16000
validation_steps: 10000
trainable_modules:
- attn1.to_q
- attn1.memory_update_layer
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
