pretrained_model_path: ./checkpoints/CompVis/stable-diffusion-v1-4
output_dir: /content/drive/Shareddrives/CS236/final_project/outputs/fewshot/lion_walking
train_data:
  video_paths:
  - training_videos/lion_walking/lion_walking_slowly.mp4
  - training_videos/lion_walking/lion_walking_slowly (1).mp4
  - training_videos/lion_walking/lioness_walking_towards_lions.mp4
  - training_videos/lion_walking/lioness_walking_near_bush.mp4
  - training_videos/lion_walking/lioness_walking_in_snow.mp4
  - training_videos/lion_walking/lion_walking_in_bush.mp4
  - training_videos/lion_walking/lion_walking_in_sunset.mp4
  - training_videos/lion_walking/lion_walking.mp4
  - training_videos/lion_walking/lion_walking_in_jungle.mp4
  prompts:
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  - lion walking
  n_sample_frames: 8
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
  - mickey mouse is skiing on the snow
  - spider man is skiing on the beach, cartoon style
  - wonder woman, wearing a cowboy hat, is skiing
  - a man, wearing pink clothes, is skiing at sunset
  video_length: 8
  width: 512
  height: 320
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 6000
checkpointing_steps: 500
resume_from_checkpoint: /content/drive/Shareddrives/CS236/final_project/outputs/fewshot/lion_walking/checkpoint-6000
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn1.memory_update_layer
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
