pretrained_model_path: ./checkpoints/CompVis/stable-diffusion-v1-4
output_dir: /content/drive/Shareddrives/CS236/final_project/outputs/fewshot/lion_walking2
train_data:
  video_paths:
  - training_videos/lion_walking/lion_walking_on_land.mp4
  - training_videos/lion_walking/lioness_walking_in_tall_grass.mp4
  - training_videos/lion_walking/lioness_walking_near_bush.mp4
  - training_videos/lion_walking/lion_walking.mp4
  - training_videos/lion_walking/lioness_walking_in_snow.mp4
  - training_videos/lion_walking/a_lion_walking_on_land.mp4
  - training_videos/lion_walking/lion_walking_near_bush.mp4
  - training_videos/lion_walking/lion_walking_in_sunset.mp4
  - training_videos/lion_walking/lion_walking_in_tall_grass.mp4
  prompts:
  - lion walking on land
  - lioness walking in tall grass
  - lioness walking near bush
  - lion walking
  - lioness walking in snow
  - a lion walking on land
  - lion walking near bush
  - lion walking in sunset
  - lion walking in tall grass
  n_sample_frames: 16
  width: 320
  height: 240
  sample_start_idx: 0
  sample_frame_rate: 2
validation_data:
  prompts:
  - mickey mouse is skiing on the snow
  - spider man is skiing on the beach, cartoon style
  - wonder woman, wearing a cowboy hat, is skiing
  - a man, wearing pink clothes, is skiing at sunset
  video_length: 16
  width: 320
  height: 240
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 2400
checkpointing_steps: 500
use_first_frame_conditioning: true
validation_steps: 10000
trainable_modules:
- attn1.to_q
- attn1.memory_update_layer
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
